news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.ce2-Tipo1_Titulo uniplus a'
      article_body:  '.field-name-body'
      article_title:  '.Encabezado-Articulo h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: ',article-content'
      article_title: '.article-header header h1 span'
  xataka:
    url: https://www.xataka.com.mx
    queries:
      homepage_article_links: '.base-asset-image a'
      article_body: '.article-content'
      article_title: '.article-header header h1 span'