new_sites:
  eluniversal:
  url: http://www.eluniversal.com.mx
  queries:
    homepage_article_links: '.ce2-Tipo1_Titulo uniplus'
  elpais:
  url: https://elpais.com
    homepage_article_links: '.headline a', '.c_m_c _pr _db'
